version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: always
    depends_on:
      - backend
