name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: \${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: \${{ secrets.AZURE_CONTAINER_REGISTRY }}/backend:latest

    - name: Build and push web image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: \${{ secrets.AZURE_CONTAINER_REGISTRY }}/web:latest

    - name: Deploy backend to Azure Container Apps
      run: |
        az containerapp update --name \${{ secrets.AZURE_BACKEND_CONTAINERAPP_NAME }} --resource-group \${{ secrets.AZURE_RESOURCE_GROUP }} --image \${{ secrets.AZURE_CONTAINER_REGISTRY }}/backend:latest --env-vars MONGODB_URI=\${{ secrets.MONGODB_URI }}

    - name: Deploy web to Azure Container Apps
      run: |
        az containerapp update --name \${{ secrets.AZURE_WEB_CONTAINERAPP_NAME }} --resource-group \${{ secrets.AZURE_RESOURCE_GROUP }} --image \${{ secrets.AZURE_CONTAINER_REGISTRY }}/web:latest
